### ISSUE TITLE
Random default reasons

### ISSUE THREAD

**Issue by SachsKaylee** [PatrickSachs/you-have-been-warned#1]
It would be fun to randomly generate a default reason for a warning/revoking a warning if the user did not specify any.

This could be done by creating a new file (e.g. `quotes.js`) and creating two arrays of strings in it: One with reasons for warnings, and one with reasons for revoking warnings.

Once that is done all that's left is selecting one of these quotes at random at the appropriate places:

https://github.com/PatrickSachs/you-have-been-warned/blob/3ec9b7d7b7ac8218e4721f6df1712e2f1e47f058/commands/warn.js#L33-L36

https://github.com/PatrickSachs/you-have-been-warned/blob/3ec9b7d7b7ac8218e4721f6df1712e2f1e47f058/commands/unwarn.js#L33-L36

**Comment by LiamTownsley** [comment]
No.
Reasons should be professional in all honesty, if no reason is provided make the reason "No reason provided."

**Comment by SachsKaylee** [comment]
Got it. I can get behind the reasoning. Thanks for your contribution, always happy to see when people take an interest in my open source projects :)
