### ISSUE TITLE
Problems with to much usage from server admins AGAINST ME SEND HELP

### ISSUE THREAD

**Issue by JakobHeubl** [PatrickSachs/you-have-been-warned#3]
Dear Mr Sachs,
please reduce the limit of warnings to 1 per week otherwise you will hear from my 
lawyer.

Kindly regards,
Jakob Heubl

**Comment by DaNeubi** [comment]
WTF.
IDK what you mean.
One per Minute would be much.

I don't understand your problem in this case.

If you need further assistance our Support is available for any concerns.

**Comment by SachsKaylee** [comment]
We have premium corporate support available starting at 2700$ a year. Please contact our sales department for details.

**Comment by JakobHeubl** [comment]
I AM THE SALES DEPARTMENT

**Comment by DaNeubi** [comment]
> at 2700$ a year

You rather mean a Month.....

**Comment by SachsKaylee** [comment]
NO YOU ARE NOT! YOU ARE FIRED FROM **SANE**!

**Comment by JakobHeubl** [comment]
AND ITS PER DAY 25000 $

**Comment by SachsKaylee** [comment]
OKAY BRING IT ON

**Comment by JakobHeubl** [comment]
I AM THE SALES DEPARTMENT WITHOUT ME YOU ARRRRREEEE GOING DOWN!

**Comment by SachsKaylee** [comment]
![if-thats-what-2jdpp7](https://user-images.githubusercontent.com/7840502/68624539-5512da00-04d7-11ea-9b0e-1810c336b38c.jpg)

**Comment by SachsKaylee** [comment]
Please refrain from using abusive language.

**Comment by DaNeubi** [comment]
![grafik](https://user-images.githubusercontent.com/6529346/68624694-b5a21700-04d7-11ea-8254-3ebea17dcaea.png)

**Comment by JakobHeubl** [comment]
HEHEHEHHEYEESYYRR
